<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact style-contact" action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>" id="contact-form"
    method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
    data-mage-init='{"validation":{}}'>
    <div class="contact-content">
        <div class="contact-form clearfix">
            <div class="fix-width map-primary">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_map_contact')->toHtml();?>
            </div>
            <div class="container ">
                <div class="row">
                    <div class="fix-width form-primary col-xl-8">
                        <div class="title">
                            <h3>Send us your message!</h3>
                        </div>
                        <fieldset class="fieldset">
                            <div class="div-flex">
                                <div class="field name required">
                                    <label class="label-contact"
                                        for="name"><span><?php /* @escapeNotVerified */ echo __('Your Name') ?></span></label>
                                    <div class="control">
                                        <input placeholder="<?php /* @escapeNotVerified */ //echo __('Name') ?>"
                                            name="name" id="name"
                                            title="<?php /* @escapeNotVerified */ echo __('Your Name') ?>"
                                            value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
                                            class="input-text" type="text" data-validate="{required:true}" />
                                    </div>
                                </div>
                                <div class="field email required">
                                    <label class="label-contact"
                                        for="email"><span><?php /* @escapeNotVerified */ echo __('Email Address') ?></span></label>
                                    <div class="control">
                                        <input placeholder="<?php /* @escapeNotVerified */ //echo __('Email') ?>"
                                            name="email" id="email"
                                            title="<?php /* @escapeNotVerified */ echo __('Email Address') ?>"
                                            value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
                                            class="input-text" type="email"
                                            data-validate="{required:true, 'validate-email':true}" />
                                    </div>
                                </div>
                            </div>
                            <div class="field telephone">
                                <label class="label-contact"
                                    for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                                <div class="control">
                                    <input placeholder="<?php /* @escapeNotVerified */ //echo __('Phone Number') ?>"
                                        name="telephone" id="telephone"
                                        title="<?php /* @escapeNotVerified */ //echo __('Phone Number') ?>" value=""
                                        class="input-text" type="text" />
                                </div>
                            </div>
                            <div class="field comment required">
                                <label class="label-contact"
                                    for="comment"><span><?php /* @escapeNotVerified */ echo __('Your Massage') ?></span></label>
                                <div class="control">
                                    <textarea
                                        placeholder="<?php /* @escapeNotVerified */ //echo __('What’s on your mind?') ?>"
                                        name="comment" id="comment"
                                        title="<?php /* @escapeNotVerified */ echo __('Your Massage') ?>"
                                        class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                                </div>
                            </div>
                            <?php echo $block->getChildHtml('form.additional.info'); ?>
                            <div class="actions-toolbar">
                                <div class="primary">
                                    <input type="hidden" name="hideit" id="hideit" value="" />
                                    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send msg') ?>"
                                        class="action submit primary">
                                        <span><?php /* @escapeNotVerified */ echo __('Send msg') ?></span>
                                    </button>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="introduce-contact col-xl-4">
                        
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-contact-us')->toHtml();?>

                    </div>
                </div>
            </div>
                <div class="fix-width store-primary col-12">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('store_contact')->toHtml();?>
                </div>
        </div>
    </div>
</form>