<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\ Framework\ App\ Action\ Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper( 'Magento\Catalog\Helper\Output' );
$_aloHelper = $this->helper( 'Magiccart\Alothemes\Helper\Data' );
$_soldHelper = $this->helper( 'Magiccart\Alothemes\Helper\Sold' );
?>
<div class="mage-magictabs mc-<?php echo $this->getTypeFilter();?>">
	<?php $total = $_productCollection->count() ?>
	<?php if (!$total): ?>
	<div class="message info empty">
		<div>
			<?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?>
		</div>
	</div>
	<?php else: ?>
	<?php
	$viewMode = 'grid';
	// $image = 'category_page_grid';
	$image = 'category_multi_grid';
	$showDescription = true;
	$templateType = \Magento\ Catalog\ Block\ Product\ ReviewRendererInterface::SHORT_VIEW;
	$pos = $block->getPositioned();
	?>
	<?php 
        $config     = $this->getWidgetCfg(); 
        // $width      = $config['widthImages'];
        // $height     = $config['heightImages'];
        $showCart       = $config['cart'];
        $showCompare    = $config['compare'];
        $showWishlist   = $config['wishlist'];
        $showReview     = $config['review'];
        $swatchesRender = $block->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setTemplate('Magiccart_Magicproduct::product/listing/renderer.phtml');
    ?>
	<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php $iterator = 1; ?>
		<div class="products list items">
			<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			<?php foreach ($_productCollection as $_product): ?>
			<?php if($iterator%7==1) echo '<div class="product product-items">'; ?>
			<?php //if( $iterator%7==1 || $iterator%7==2 || $iterator%7==4 || $iterator%7==6 )
			if($iterator%7==1)
				echo '<div class="sub-item item product-item item-product-right">';
			if( $iterator%7==2 )
				echo '<div class="sub-item item product-item item-product-left">';
                  
                /* 1-2-2-2 */ ?>
			<div class="product-item-info" data-container="product-grid">
				<div class="per-product">
					<?php
					$productImage = $block->getImage( $_product, $image );
					if ( $pos != null ) {
						$position = ' style="left:' . $productImage->getWidth() . 'px;'
						. 'top:' . $productImage->getHeight() . 'px;"';
					}
					?>
					<div class="images-container">
						<?php 
                            if($iterator%7!=1):
                                $product_label = $_aloHelper->getLabels($_product); 
                                echo $product_label ? '<div class="product-label">' . $product_label . '</div>' : ''; 
                            endif;
                        ?>
						<?php // Product Image ?>
						<div class="product-hover">
							<?php //echo $_aloHelper->getLabels($_product); ?>
							<?php //echo $_aloHelper->getTimer($_product); ?>
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>
							<div class="link-view">
								<button type="button" class="quickview <?php echo $_product->getTypeId() ?>" title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure()) ) ?>'});"><span><i class="fa fa-search icons"></i><?php echo __('Quick View')?></span>
                                </button>
							</div>
						</div>
						<div class="products-textlink clearfix">
							<h2 class="product-name product-item-name">
								<a class="product-item-link" title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" href="<?php echo $_product->getProductUrl() ?>">
									<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h2>
							
							<!-- description -->
							<?php if ($showDescription && $iterator%7==1):
							echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
							?>
							<?php endif; ?>
							<!-- end description -->
							
							<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
							<div class="product details product-item-details products-textlink clearfix">
	                            <?php echo $block->getProductPrice($_product) ?>
	                            <?php echo $swatchesRender->setProduct($_product)->toHtml() ?>
	                        </div>
							<?php 
                                if($iterator%7==1):
                                $timer = $_aloHelper->getTimer($_product);
								if($timer):
									$sold   = $_soldHelper->getSoldQty($_product);
                                    $qty  = (int) $this->getProductQty($_product);
                                    $total_sale = $qty + $sold;
                                    $percent = $qty > 0 ? round(($qty/$total_sale) * 100) : 0;
                                    ?>
									<div class="product-deal-special-progress">
										<div class="deal-stock-label">
											<span class="stock-available text-left">
												<?php echo __('Available') ?>:
												<strong>
													<?php echo $qty ?>
												</strong>
											</span>
											<span class="stock-sold text-right">
												<?php echo __('Already Sold') ?>:
												<strong>
													<?php echo $sold ?>
												</strong>
											</span>
										</div>
										<div class="progress" style="height:13px;">
		                                    <div class="progress-bar bg-green" role="progressbar" style="width: <?php echo $percent ?>%" aria-valuenow="<?php echo $percent ?>" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
									<?php
										echo $timer;
									endif;
								endif;
                                    
							?>
							<?php echo $showReview ? $block->getReviewsSummaryHtml($_product, $templateType) : ''; ?>

							
                            <?php echo $block->getProductDetailsHtml($_product); ?>
                           	<!-- cart -->
							<?php if ($showCart): ?>
							<div class="actions-primary actions-cart" <?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
								<?php if ($_product->isSaleable()): ?>
								<?php $postParams = $block->getAddToCartPostParams($_product); ?>
								<form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
									<input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
									<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php  echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
									<?php echo $block->getBlockHtml('formkey')?>
									<button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary button btn-cart">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
								
								</form>
								<?php else: ?>
								<?php if ($_product->getIsSalable()): ?>
								<div class="stock available">
									<span>
										<?php echo __('In stock') ?>
									</span>
								</div>
								<?php else: ?>
								<div class="stock unavailable">
									<span>
										<?php echo __('Out of stock') ?>
									</span>
								</div>
								<?php endif; ?>
								<?php endif; ?>
							</div>
							<?php endif; ?>
							<!-- end cart -->
						</div>

						<?php if ($showWishlist || $showCompare || $showCart): ?>
						<div class="actions-no hover-box">
							<div class="product actions clearfix" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
								<div class="show-box">
								
									<!-- wishlist/compare -->
									<?php if ($showWishlist || $showCompare): ?>
									<div data-role="add-to-links" class="actions-secondary add-to-links" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
										<a href="#" class="action towishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
														<i class="icon fa fa-heart-o"></i><?php /* @escapeNotVerified */ echo __('Wishlist') ?>
													</a>
									
										<?php endif; ?>

										<?php if ($showCompare): $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
													?>
										<a href="#" class="action tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
														<i class="icon fa fa-bar-chart"></i><?php /* @escapeNotVerified */ echo __('Compare') ?>
													</a>
									
										<?php endif; ?>
									</div>
									<?php endif; ?>
									<!-- end wishlist/compare -->
								</div>
							</div>
						</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
			<?php 
			//if( $iterator%7==1 || $iterator%7==3 || $iterator%7 == 5 || $iterator%7==0 || $iterator==$total  ) 
			if( $iterator%7==1 || $iterator%7==0  || $iterator==$total  ) 
				echo '</div>'; /* 1-2-2-2 */ ?>
			<?php if($iterator%7==0 || $iterator==$total) echo '</div>'; $iterator++;?>
			<?php endforeach; ?>
		</div>
	</div>
	<?php if (!$block->isRedirectToCartEnabled()) : ?>
	<script type="text/x-magento-init">
		{ "[data-role=tocart-form], .form.map.checkout": { "catalogAddToCart": {} } }
	</script>
	<?php endif; ?>
	<?php endif; ?>
</div>