<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2018-03-14 23:53:41
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php /* @escapeNotVerified */ echo $selector?> magicproduct autoplay">
	<?php 
		$timer  = $this->getData('countdown');
		$timer = $timer ?  date('n/d/Y', strtotime($timer)) : 0;
		if($timer) : 
	?>
		<div class="alo-count-down count-down-time">
			<!-- <span class="icon-clock fa fa-clock-o"><span class="hidden">hidden</span></span> -->
			<p class="text-countdown-h6">
				<?php echo __('Hurry up! ') ?><span><?php echo __('Offers end in:') ?></span>
			</p>
			<div class="countdown caption" data-timer="<?php /* @escapeNotVerified */ echo $timer ?>"></div>
			<p class="all">
				<a href="#"><?php echo __('View all items ') ?><i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
			</p>
		</div>
	<?php endif ?>
<?php
$tabs = $this->getTabs();
$numTabs = count($tabs);
if($numTabs): ?>
    <div class="block-title-tabs clearfix">
	<span class="toggle-tab mobile"><i class="fa fa-bars"></i></span>
	<ul class="magictabs toggle-content" data-ajax ='<?php /* @escapeNotVerified */ echo $this->getAjaxCfg() ?>'>
	<?php $activated = $this->getTabActivated();
		$limit = $this->getLimit();
		$single = ($numTabs ==1) ? 'single' : '';
		foreach ($tabs as $type => $name):
			$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
			$status .= ($type == $activated) ? " activated $single" : '';
			/* @escapeNotVerified */ echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
		endforeach;
	?>
	</ul>
    </div>
<?php endif ?>
	<div class="ajax_loading" style="display:none" data-url="<?php /* @escapeNotVerified */ echo $this->getUrl('magicproduct/index/product', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
	<div class="box-product-content clearfix">
		<div class="content-products" 
		<?php foreach ($this->getFrontendCfg() as $opt) :?>
			data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
		<?php endforeach;?>        
		>
		<?php 
			$timer = $this->getTimer();
			if($timer) echo $this->getContent('product/gridtimer.phtml');	
			else echo $this->getContent('product/grid2.phtml');	
		?>
		</div>
	</div>
</div>
