<?php
if(!$this->getEnabled()) return;
$selector = 'alo-content-'.rand(0,999999999);
$testimonials = $this->getTestimonials();
if(!count($testimonials)) return;
?>
<div class="<?php /* @escapeNotVerified */ echo $selector ?>">
    <div class="block-testimonial">
        <?php echo $this->getTitle() ? '<h3 class="block-title title item">' . '<span>' . $this->escapeHtml($this->getTitle()) . '</span>' . '</h3>' : '' ?>
    </div>
    <div class="block-content">
        <div class="testimonial" data-fade='false' <?php foreach ($this->getFrontendCfg() as $opt) :?>
            data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
            <?php endforeach;?>>
            <?php $i=0; foreach ($testimonials as $testimonial) :?>
            <div class="item">
                <div class="testimonial_text">
                    <div class="content sub-text"><?php echo $this->escapeHtml($testimonial->getText()); ?></div>
                </div>
                <div class="inner-customer clearfix">
                    <div class="inner-left">
                        <div class="customer">
                            <a href="<?php echo $block->getUrl('testimonial'); ?>">
                                <img class="avatar img-responsive"
                                    src="<?php echo $this->escapeUrl($this->getImage($testimonial)) ?>"
                                    alt="<?php echo __($this->escapeHtml($testimonial->getName())) ?>"
                                    title="<?php echo __($this->escapeHtml($testimonial->getName())) ?>" />
                            </a>
                        </div>
                    </div>
                    <div class="inner-right">
                        <div class="magiccart-testimonial-rating">
                            <div class="rating-result">
                                <div class="field-summary_rating">
                                    <span class="rating-box" style="display:block;">
                                        <span style="display:block; width:<?php echo $testimonial->getData('rating_summary')*20; ?>%;" class="rating"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <p class="job"><?php echo __($this->escapeHtml($testimonial->getData('job')))?></p>
                        <p class="name title-name"><?php echo $this->escapeHtml($testimonial->getName()); ?></p>
                    </div>
                </div>

            </div>
            <?php endforeach ?>
        </div>
    </div>
</div>

<script type="text/javascript">
require([
    'jquery',
    'magiccart/slick',
    'alothemes',
], function($, slick, alothemes) {
    var testimonial = $('.<?php echo $selector ?> .testimonial');
    if (testimonial.length) $('head').append(magicproduct(testimonial, '.item'));
});
</script>