<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2018-03-14 23:53:41
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class="<?php /* @escapeNotVerified */ echo $selector?> magicproduct autoplay">
    <div class="block-title-tabs clearfix">

        <?php
$tabs = $this->getTabs();
$numTabs = count($tabs);
$myTitle = $this->getTitle();
if($numTabs): ?>

        <div class="magictabs" data-ajax='<?php /* @escapeNotVerified */ echo $this->getAjaxCfg() ?>'>
            <?php $activated = $this->getTabActivated();
		$limit = $this->getLimit();
		$single = ($numTabs ==1) ? 'single' : '';
		foreach ($tabs as $type => $name):
			$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
			$status .= ($type == $activated) ? " activated $single" : '';
			/* @escapeNotVerified */ echo '<p class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span><span class ="my-title">'.__($myTitle).'</span></p>';
		endforeach;
	?>
	<?php 
		$timer  = $this->getData('countdown');
		$timer = $timer ?  date('n/d/Y', strtotime($timer)) : 0;
		if($timer) : 
	?>
        <div class="alo-count-down count-down-time">
            <span class="icon-clock"><span class="hidden">hidden</span></span>
            <div class="countdown caption" data-timer="<?php /* @escapeNotVerified */ echo $timer ?>"></div>
        </div>
        <?php endif ?>
        </div>
        <!-- <h3 class="title"><?php echo __($this->getTitle()); ?></h3> -->
        
    </div>
    <?php endif ?>
    <?php if($type == 'new') $type = 'newproduct'; ?>
    <!-- <a href="<?php /* @escapeNotVerified */ echo $this->getUrl("magicproduct/$type", array('_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure()) ) ?>"
        class="all-products"><?php /* @escapeNotVerified */ echo __('View all') ?></a> -->
    <div class="ajax_loading" style="display:none"
        data-url="<?php /* @escapeNotVerified */ echo $this->getUrl('magicproduct/index/product', array('_secure'=>$this->getRequest()->isSecure()))?>">
    </div>
    <div class="box-product-content clearfix">
        <div class="box-product">
            <div class="content-products" <?php foreach ($this->getFrontendCfg() as $opt) :?>
                data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
                <?php endforeach;?>>
                <?php 
				$timer = $this->getTimer();
				if($timer) echo $this->getContent('product/gridtimer_special_offer.phtml');	
				else echo $this->getContent('product/grid.phtml');	
			?>
            </div>
        </div>
    </div>
</div>
