<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if (!$_postCollection->count()) return ?>
<div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <div class="block-title">
        <strong><?php echo __('Recent Posts') ?></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_postCollection as $_post) { ?>
        <div class="item">
            <a class="post-item-link" href="<?php echo $_post->getPostUrl() ?>">
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <img src="<?php echo $featuredImage ?>" alt="<?php echo $block->escapeHtml($_post->getTitle()) ?>" />
                <?php } ?>
            </a>
            <div class="info">
                <div class="title">
                    <a href="<?php echo $_post->getPostUrl() ?>">
                        <h3><?php echo $block->escapeHtml($_post->getTitle()) ?></h3>
                    </a>
                </div>
                <div class="post-meta">
                    <?php if($_post->getAuthor()) : ?>
                    <div class="post-author">
                        <?php echo __('By:'); ?>
                        <a href="#"><?php echo $_post->getAuthor()->getName() ?></a>
                    </div>
                    <?php endif ?>
                    <div class="post-posed-date">
                        <span class="value"><?php echo __(' - '); ?><?php echo $_post->getPublishDate('M d, Y') //'F d, Y' ?></span>
                    </div>
                </div>
            </div>
        </div>

        <?php } ?>
    </div>
</div>