<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2016-10-22 09:43:04
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php echo $selector?> magicproduct megashop autoplay">
<?php
$tabs = $this->getTabs();
$relatedTabs = $this->getRelatedTabs();
$numTabs = count($tabs);
$isAjax = $this->getAjax();
$banner = $this->getBanner();
echo '<h3 class="title">'.$this->getCatName().'</h3>';
if($numTabs): ?>
    <span class="toggle-tab mobile" style="display:none"><i class="fa fa-bars"></i></span>
    <div class="block-title-tabs toggle-content">
		<ul class="magictabs" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
		<?php $activated = $this->getTabActivated();
			$limit = $this->getLimit();
			$single = ($numTabs ==1) ? 'single' : '';
			foreach ($tabs as $type => $name):
				$status  = (!$isAjax || $activated ==$type) ? 'loaded' : '';
				$status .= ($type == $activated) ? " activated $single" : '';
				echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
			endforeach;
			/*foreach ($relatedTabs as $cat):
				echo $isAjax ? '<li class="item cat" data-type ="'.$cat->getEntityId().'"><span class ="title">'.$cat->getName().'</span></li>' : '<li class="item cat" data-type ="'.$cat->getEntityId().'"><a href="'.$cat->getUrl().'"><span class ="title">'.$cat->getName().'</span></a></li>';
			endforeach;*/
		?>
		</ul>
    </div>
<?php endif ?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($this->getIdentifier())->toHtml();?>
	<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/catalog', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
	
	<div class="product-featured clearfix">
	    <div class="product-featured-content">
			<?php if($banner): ?>
				<div class="banner-featured">
					<div class="promotion" 
						data-autoplay="false"
						data-arrows="false"
						data-autoplay-speed="3000"
						data-dots="true"
						data-infinite="true"
						data-vertical="false"
						data-vertical-swiping="false"
						data-rows="1"
						data-slides-to-show="1"
						data-swipe-to-slide="true"
					>
			        <?php $i=0; foreach ($banner as $item) :?>
			            <?php
			                if($item['disabled']) continue;
			                $image = $item['file'];
			                $type  = $item['media_type'];
			                $label = $item['label'];
			            ?>
						<div class="item <?php echo $type ?>"
			                <?php echo ($item['video_url']) ? 'data-video="'. $item['video_url'] .'"' : ''; ?> 
			            >
			    			<a href="<?php echo isset($item['link']) ? $item['link'] : '#'; ?>">
			    				<img class="img-responsive" src="<?php echo $this->getImage($image)?>" alt="<?php echo __($label) ?>" title="<?php echo __($label) ?>" />
			    			</a>
							<?php //echo isset($item['caption']) ? $item['caption'] : ''; ?>

						</div>
			        <?php endforeach ?>
					</div>
				</div>
			<?php endif ?>
			<div class="content-products" 
			<?php foreach ($this->getFrontendCfg() as $opt) :?>
				data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
			<?php endforeach;?>        
			>
			<?php 
				$timer = $this->getTimer();
				if($timer) echo $this->getContent('catalog/gridtimer.phtml');	
				else echo $this->getContent('catalog/grid.phtml');	
			?>
			</div>
		</div>
	</div>
</div>
