<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php 
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
 $customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
?>
<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&subset=latin-ext"
    rel="stylesheet">
<header class="page-header alothemes">
    <div class="header">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="mobile-center top-left col-xl-6 col-lg-6 col-md-6 col-sm-12">
                        <div class="hot-contact">
                            <div class="hotline">
                                <div class="contact">
                                    <ul>
                                        <li class="email"><?php echo $this->getChildHtml('welcometop'); ?></li>
                                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('hotline')->toHtml();?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="top-right mobile-center col-xl-6 col-lg-6 col-md-6 col-sm-12">
                        <div class="header-top-link">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-information-right')->toHtml();?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-content menu-mobile">
            <div class="container">
                <div class="row row-header-content">
                    <div class="nav-toggle-mobile d-xl-none col-lg-4 col-md-4 col-sm-4 col-4">
                        <div class="nav-toggle-main">
                            <span data-action="toggle-nav" class="action nav-toggle">
                                <span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span>
                            </span>
                        </div>
                    </div>
                    <div class="content-logo col-xl-3 col-lg-4 col-md-4 col-sm-4 col-4">
                        <div class="header-logo">
                            <?php echo $this->getChildHtml('logo'); ?>
                        </div>
                    </div>
                    <div class="content-search col-xl-6 col-lg-4 col-md-4 col-sm-12">
                        <div class="search-area header-search">
                            <?php echo $this->getChildHtml('top.search'); ?>
                        </div>
                    </div>
                    <div class="content-cart col-xl-3 col-lg-4 col-md-4 col-sm-4 col-4">
                        <div class="tool-header">
                            <div class="tool-header-link">
                                <div class="top-links">
                                    <?php echo $this->getChildHtml('account.links'); ?>
                                </div>
                            </div>
                            <div class="tool-cart">
                                <?php echo $this->getChildHtml('minicart'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-bottom header-sticker">
            <div class="container">
                <div class="row row-header-bottom">
                    <div class="header-vertical-menu col-lg-3 col-md-3 col-sm-12 col-12">
                        <div class="sum-menu">
                            <?php echo $this->getChildHtml('vmenu.topnav'); ?>
                        </div>
                    </div>
                    <div class="content-menu col-lg-7 col-md-7 col-sm-12 col-12">
                        <div class="menu">
                            <?php echo $this->getChildHtml('navigation.sections'); ?>
                            <div class="no-display" style="display:none"><?php echo $this->getChildHtml('top.links2'); ?></div>	
                            <?php echo $this->getChildHtml('catalog.topnav'); ?>
                        </div>
                    </div>
                    <div class="sum-language-currency col-lg-2 col-md-2 col-sm-12 col-12">
                        <div class="header-top-link">
                            <div class="header-setting tool-setting">
                                <?php echo $this->getChildHtml('store_language'); ?>
                                <?php echo $this->getChildHtml('currency'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>